services:
  payment-db:
    build:
      context: ./payment-service
      dockerfile: Dockerfile.payment-db
    image: payment-db:1.0
    container_name: payment-db
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: paymentuser
      POSTGRES_PASSWORD: paymentpass
    ports:
      - "5434:5432"   # host 5436 -> container 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paymentuser -d paymentdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile.payment-service
    image : payment-service:latest
    container_name: payment-service
    depends_on:
      payment-db:
        condition: service_healthy
    environment:
      PAYMENT_DB_HOST: payment-db
      PAYMENT_DB_PORT: 5432
      PAYMENT_DB_NAME: paymentdb
      PAYMENT_DB_USER: paymentuser
      PAYMENT_DB_PASSWORD: paymentpass
    ports:
      - "9083:9083"
    volumes:
      - ./logs/payment:/app/payment-logs
