server:
  port: 9083

spring:
  datasource:
    url: jdbc:postgresql://${PAYMENT_DB_HOST:payment-db}:${PAYMENT_DB_PORT:5432}/${PAYMENT_DB_NAME:paymentdb}
    username: ${PAYMENT_DB_USER:paymentuser}
    password: ${PAYMENT_DB_PASSWORD:paymentpass}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: INFO
  file:
    name: /app/payment-logs/payment-service.json


# Resilience4j in-memory rate limiting
resilience4j.ratelimiter:
  instances:
    paymentChargeLimiter:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
    paymentRefundLimiter:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
